# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ZweqYRZs3Q4jriWx1726Ri4XGPrf6Ob
"""

import pandas as pd
from sklearn.cluster import KMeans
from subprocess import run


data = pd.read_csv('res_dpre.csv')


selected_columns = ['Age', 'Rating']

kmeans = KMeans(n_clusters=3, random_state=42)
data['cluster'] = kmeans.fit_predict(data[selected_columns])

cluster_counts = data['cluster'].value_counts()
cluster_counts.to_csv('k.txt', header=False)
cluster_counts


run(["bash", "final.sh"])

