# -*- coding: utf-8 -*-
"""Vis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mPwdydbNUnV6b3aMlm559p1ObZMoLb4r
"""

import pandas as pd
import matplotlib.pyplot as plt
from subprocess import run

data = pd.read_csv('res_dpre.csv')

department_reviews = data['Labeled Department Name'].value_counts()

plt.figure(figsize=(10, 6))
department_reviews.plot(kind='bar', color='skyblue')
plt.title('Number of Reviews per Department')
plt.xlabel('Department')
plt.ylabel('Number of Reviews')
plt.xticks(rotation=45)
plt.tight_layout()


plt.savefig('vis.png')

run(["python3", "model.py", 'res_dpre.csv'])



